apiVersion: v2
name: better-spring-boot
description: Unified deployment of individual spring boot applications
type: application
version: 0.1.0
appVersion: "3.4.1"
keywords:
  - java
  - spring-boot
maintainers:
  - name: Omar Sood
    email: goatfryed@gmail.com
home: https://github.com/goatfryed/helm-charts/
sources:
  - https://github.com/goatfryed/helm-charts/
