apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "better-spring-boot.fullname" . }}
  labels:
    {{- include "better-spring-boot.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "better-spring-boot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "better-spring-boot.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "better-spring-boot.deployment.podRecreationStrategy" . | nindent 8}}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "better-spring-boot.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: "spring-boot"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ required "image.repository must be provided" .Values.image.repository }}:{{ .Values.image.tag | default .Values.appVersion | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if and .Values.debugDeployment.enabled .Values.debugDeployment.overrideCommand }}
          command:
            {{- toYaml .Values.debugDeployment.overrideCommand | nindent 12 }}
          {{- end }}
          {{- with (include "better-spring-boot.deployment.containerEnv" .) }}
          env:
            {{- . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.spring.serverPort | default .Values.service.port }}
              protocol: TCP
            - name: http-management
              containerPort: {{ .Values.spring.managementPort | default .Values.spring.serverPort | default .Values.service.port }}
              protocol: TCP
          {{- include "better-spring-boot.deployment.appHealthChecks" . | nindent 10 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: helm-application-properties
              mountPath: /app/config/helm-config
              readOnly: true
            {{- include "better-spring-boot.userConfigMounts" . | nindent 12 }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- with  .Values.deployment.extraContainers }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
      {{- with .Values.deployment.initContainers }}
      initContainers:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      volumes:
        - name: helm-application-properties
          configMap:
            name: {{ include "better-spring-boot.propertiesConfigMapName" . }}
        {{- include "better-spring-boot.userConfigVolumes" . | nindent 8 }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- define "better-spring-boot.deploymentactiveProfiles" -}}
{{
  (include "better-spring-boot.deploymentdebugProfiles" .)
  | default (include "better-spring-boot.deploymentuserProfiles" .)
  | default (include "better-spring-boot.deploymentdefaultProfiles" .)
}}
{{- end -}}

{{- define "better-spring-boot.deploymentuserProfiles" -}}
{{ $activeProfiles := .Values.spring.profiles.active }}
{{- if not $activeProfiles }}
{{- "" -}}
{{- else if eq (typeOf $activeProfiles) "string" -}}
  {{ $activeProfiles }}
{{- else if eq (typeOf $activeProfiles) "[]interface {}" -}}
  {{ join ", " $activeProfiles }}
{{- else -}}
  {{ required "Illegal argument for spring.container.activeProfiles" nil }}
{{- end -}}
{{- end -}}

{{- define "better-spring-boot.deploymentdefaultProfiles" -}}
{{- $profiles := list -}}
{{- range $key,$value := .Values.spring.config -}}
{{- $profiles = append $profiles $key -}}
{{- end -}}
{{- join ", " $profiles -}}
{{- end -}}

{{- define "better-spring-boot.deploymentdebugProfiles" -}}
{{ $activeProfiles := .Values.debugDeployment.overrideProfiles }}
{{- if not .Values.debugDeployment.enabled -}}
{{- "" -}}
{{- else if not $activeProfiles -}}
{{- "" -}}
{{- else if eq (typeOf $activeProfiles) "string" -}}
  {{ $activeProfiles }}
{{- else if eq (typeOf $activeProfiles) "[]interface {}" -}}
  {{ join ", " $activeProfiles }}
{{- else -}}
  {{ required "Illegal argument for debugDeployment.overrideProfiles" nil }}
{{- end -}}
{{- end -}}

{{- define "better-spring-boot.userConfigVolumeName" -}}
user-application-properties-{{- . -}}
{{- end -}}

{{- define "better-spring-boot.userConfigVolumes" -}}
{{- range $profile,$config := .Values.spring.config -}}
{{- if $config.configMap -}}
- name: {{ include "better-spring-boot.userConfigVolumeName" $profile }}
  configMap:
    name: {{ required (printf "spring.config.%s.configMap.name must be given" $profile) $config.configMap.name }}
{{ else if $config.secret -}}
- name: {{ include "better-spring-boot.userConfigVolumeName" $profile }}
  secret:
    secretName: {{ required (printf "spring.config.%s.configMap.name must be given" $profile) $config.secret.name }}
{{ end -}}
{{- end -}}
{{- end -}}

{{- define "better-spring-boot.userConfigMounts" -}}
{{- range $profile,$config := .Values.spring.config -}}
{{- if and $config.configMap $config.secret -}}
  {{ fail (printf "use either configMap or secret in spring.config.%s" $profile) }}
{{- else if $config.configMap -}}
- name: {{ include "better-spring-boot.userConfigVolumeName" $profile }}
  mountPath: /app/config/config-map/application-{{ $profile }}.{{ default "yaml" $config.configMap.type }}
  subPath: {{ default "application.yaml" $config.configMap.key }}
  readOnly: true
{{ else if $config.secret -}}
- name: {{ include "better-spring-boot.userConfigVolumeName" $profile }}
  mountPath: /app/config/config-map/application-{{ $profile }}.{{ default "yaml" $config.secret.type }}
  subPath: {{ default "application.yaml" $config.secret.key }}
  readOnly: true
{{ end -}}
{{- end -}}
{{- end -}}
