{{- define "easy-spring-boot.deployment.podRecreationStrategy" -}}
{{- $strategy := default "never" .Values.deployment.recreatePodStrategy }}
{{- if eq $strategy "values-changed" }}
{{- with ( include "easy-spring-boot.deployment.helmAppConfigChecksum" . ) }}
release/checksum-app-config: {{ . }}
{{- end }}
{{- else if eq $strategy "always" }}
release/roll-me: {{ print .Release.Revision "-" (randAlphaNum 5) | quote }}
{{- end }}
{{- end }}

{{- define "easy-spring-boot.deployment.helmAppConfigChecksum" }}
  {{- $activeProfiles := include "easy-spring-boot.deploymentactiveProfiles" . }}
  {{- $activeProfilesList :=  (regexSplit ", ?" $activeProfiles -1) }}
  {{- $appConfig := include (print $.Template.BasePath "/configMap.appConfig.yaml") . | fromYaml }}
  {{- if $appConfig.data }}
    {{- $activeConfig := dict }}
    {{- range $activeProfile := (sortAlpha $activeProfilesList) -}}
      {{- $configFileName := include "easy-spring-boot.appConfigMap.configFileName" $activeProfile }}
      {{- $activeConfig := merge $activeConfig (pick $appConfig.data $configFileName) }}
    {{- end }}
    {{- $activeConfig | toYaml | sha1sum }}
  {{- end }}
{{- end }}

{{- define "easy-spring-boot.deployment.springApplicationName" }}
{{- .Values.spring.applicationName | default .Values.fullnameOverride | default .Release.Name }}
{{- end}}

{{- define "easy-spring-boot.deployment.containerEnv" }}
  {{- $envVars := .Values.spring.environmentVariable }}
  {{- $envVars = omit $envVars
        "MANAGEMENT_SERVER_PORT"
        "SERVER_PORT"
        "SPRING_APPLICATION_NAME"
        "SPRING_CONFIG_ADDITIONAL_LOCATION"
        "SPRING_PROFILES_ACTIVE"
  }}
  {{- range $key, $value := $envVars }}
  {{- if ne $value nil }}
- name: {{ $key }}
  value: {{ default "" $value | toString | toJson }}
  {{- end }}
  {{- end }}
  {{- $activeProfiles := include "easy-spring-boot.deploymentactiveProfiles" . }}
  {{- with $activeProfiles }}
- name: SPRING_PROFILES_ACTIVE
  value: {{ default "''" $activeProfiles }}
  {{- end }}
{{- if not (and (kindIs "bool" .Values.spring.applicationName) (eq .Values.spring.applicationName false)) }}
- name: SPRING_APPLICATION_NAME
  value: {{ include "easy-spring-boot.deployment.springApplicationName" . }}
{{- end }}
- name: SPRING_CONFIG_ADDITIONAL_LOCATION
  value: optional:/app/config/*/
- name: SERVER_PORT
  value: {{ include "easy-spring-boot.deployment.applicationServerPort" . | toString | toJson }}
- name: MANAGEMENT_SERVER_PORT
  value: {{ include "easy-spring-boot.deployment.managementServerPort" . | toString | toJson }}
{{- end }}

{{- define "easy-spring-boot.deployment.applicationServerPort" }}
{{- .Values.spring.serverPort | default .Values.service.port }}
{{- end }}

{{- define "easy-spring-boot.deployment.managementServerPort" }}
{{- .Values.spring.managementPort | default (include "easy-spring-boot.deployment.applicationServerPort" .) }}
{{- end }}

{{- define "easy-spring-boot.deployment.appHealthChecks" }}
{{- if and .Values.debugDeployment.enabled (not .Values.debugDeployment.healthChecksEnabled) }}
{{- else }}
{{- $livenessProbe := mergeOverwrite (deepCopy .Values.healthChecks.defaults) .Values.healthChecks.livenessProbe }}
{{- if $livenessProbe.enabled }}
livenessProbe:
  {{- omit $livenessProbe "enabled" | toYaml | nindent 2 }}
{{- end}}
{{- $startupProbe := mergeOverwrite (deepCopy .Values.healthChecks.defaults) .Values.healthChecks.startupProbe }}
{{- if $startupProbe.enabled }}
startupProbe:
  {{- omit $startupProbe "enabled" | toYaml | nindent 2 }}
{{- end}}
{{- $readinessProbe := mergeOverwrite (deepCopy .Values.healthChecks.defaults) .Values.healthChecks.readinessProbe }}
{{- if $readinessProbe.enabled }}
readinessProbe:
  {{- omit $readinessProbe "enabled" | toYaml | nindent 2 }}
{{- end}}
{{- end }}
{{- end }}