name: Release Helm Chart

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  test-before-release:
    uses: ./.github/workflows/test.yml
    with:
      chart-dir: charts/spring-boot

  release:
    needs: test-before-release
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Helm
      - name: Setup Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      # Step 3: Create the target directory
      - name: Create Target Directory
        run: |
          mkdir -p build/pages/charts

      # Step 4: Package the Helm chart
      - name: Package Helm Chart
        run: |
          helm package charts/spring-boot --destination build/pages/charts

      # Step 5: Generate the Helm repository index
      - name: Generate Index
        env:
          CHART_REPO_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
        run: |
          helm repo index build/pages/charts --url $CHART_REPO_URL

      # Step 6: Publish to GitHub Pages
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/charts
