name: Verify

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  verify:
    uses: ./.github/workflows/test.yml
    with:
      chart-dir: charts/spring-boot
